SELECT APNT_NO, PT_NAME, PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS A
JOIN PATIENT AS P USING(PT_NO)
JOIN DOCTOR AS D ON A.MDDR_ID = D.DR_ID
WHERE DATE_FORMAT(A.APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND D.MCDP_CD = "CS" AND A.APNT_CNCL_YN = "N"
ORDER BY APNT_YMD;