SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME FROM ANIMAL_INS AS INS
JOIN ANIMAL_OUTS AS OUTS
USING(ANIMAL_ID)
WHERE INS.SEX_UPON_INTAKE LIKE "%Intact%" AND OUTS.SEX_UPON_OUTCOME NOT LIKE "%Intact%"