SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, IF(SCORE IS NULL, 0, SCORE) AS SCORE
FROM REST_INFO AS I
LEFT JOIN (SELECT ROUND(AVG(REVIEW_SCORE), 2) AS SCORE, REST_ID FROM REST_REVIEW GROUP BY REST_ID) AS R
USING(REST_ID)
WHERE ADDRESS LIKE "서울%" AND SCORE IS NOT NULL
ORDER BY SCORE DESC, FAVORITES DESC;