SELECT *
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID FROM (
        SELECT COUNT(HOST_ID) AS COUNT, HOST_ID
        FROM PLACES
        GROUP BY HOST_ID
        HAVING COUNT >= 2
    ) AS A
)
ORDER BY ID;