SELECT S.ROUTE as ROUTE, 
CONCAT(S.TOTAL_DISTANCE, "km") as TOTAL_DISTANCE,
CONCAT(S.AVERAGE_DISTANCE, "km") as AVERAGE_DISTANCE
FROM (SELECT ROUTE, ROUND(SUM(D_BETWEEN_DIST), 1) as TOTAL_DISTANCE, 
ROUND(AVG(D_BETWEEN_DIST), 2) as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY TOTAL_DISTANCE DESC) as S