WITH CTE AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXSIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE))

SELECT C.YEAR AS YEAR, (C.MAXSIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E
JOIN CTE C ON YEAR(E.DIFFERENTIATION_DATE) = YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;