SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW AS R
LEFT JOIN MEMBER_PROFILE AS P
USING(MEMBER_ID)
WHERE MEMBER_ID
IN (SELECT MEMBER_ID 
    FROM (SELECT COUNT(MEMBER_ID) AS COUNT, MEMBER_ID
          FROM REST_REVIEW
          GROUP BY MEMBER_ID
          ORDER BY COUNT DESC
          LIMIT 1)
    AS C)
ORDER BY REVIEW_DATE, REVIEW_TEXT;